version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: web:django
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000